CREATE TABLE IF NOT EXISTS USERS (
    username VARCHAR(255) NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS REVIEWS (
    id INTEGER NOT NULL PRIMARY KEY,
    username VARCHAR(255) REFERENCES USERS (username),
    contentType VARCHAR(20),
    contentId VARCHAR(255),
    review VARCHAR(255),
    rating VARCHAR(10)
);